language: go
go: 1.13.x
notifications:
  email: markusgilg@outlook.de
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - github.com/onsi/gomega
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken gvoncJ0n5yDL68I2IKscHoPfXH38Ktkyr
