language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

jobs:
  include:
    - stage: build
      script: go build
    - stage: test
      script: go test -v ./... -coverprofile=gotools.coverprofile